export const GET_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS";
export const GET_PRODUCTS_PENDDING = "GET_PRODUCTS_PENDDING";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";

export const GET_PRODUCTDETAIL_SUCCESS = "GET_ALL_PRODUCTDETAIL";
export const GET_PRODUCTDETAIL_PENDDING = "GET_PRODUCTDETAIL_PENDDING";
export const GET_PRODUCTDETAIL_ERROR = "GET_PRODUCTDETAIL_ERROR";

export const SORT_PRODUCTS_HIGHER = "SORT_PRODUCTS_HIGHER";
export const SORT_PRODUCTS_LOWER = "SORT_PRODUCTS_LOWER";
export const SORT_PRODUCTS_FIT = "SORT_PRODUCTS_FIT";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_TO_CART = "REMOVE_TO_CART";
export const REMOVE_TO_ONE_CART = "REMOVE_TO_ONE_CART";
export const CHANGE_COUNT_CART = "CHANGE_COUNT_CART";
export const REMOVE_COUNT_CART = "REMOVE_COUNT_CART";

export const OPEN_CART = "OPEN_CART";
export const CLOSE_CART = "CLOSE_CART";
